name: Go Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read Go version from go.mod
      run: |
        export GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+' go.mod | awk '{print $2}')
        echo "Go version in go.mod: $GO_VERSION"
        echo "##[set-output name=GO_VERSION;]$GO_VERSION"
      id: go_version

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.go_version.outputs.GO_VERSION }}

    - name: Run tests
      run: |
        go mod download
        go test -v ./...

    - name: Check for test failures
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed. Please fix the issues before pushing to this branch."
          exit 1
        fi
