name: Push Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run tests
      run: |
        go mod download
        go test -v ./...

    - name: Check for test failures
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed. Please fix the issues before pushing to this branch."
          exit 1
        fi
